version: '3.5'

services:
  traefik:
    image: traefik:v2.2
    restart: always
    container_name: traefik
    ports:
        - "80:80" # <== http
        # - "8080:8080" # <== :8080 is where the dashboard runs on
        - "443:443" # <== https
    command:
    #### These are the CLI commands that will configure Traefik and tell it how to work! ####
        ## API Settings - https://docs.traefik.io/operations/api/, endpoints - https://docs.traefik.io/operations/api/#endpoints ##
        # - --api.insecure=false # <== Enabling insecure api, NOT RECOMMENDED FOR PRODUCTION
        - --api=true
        - --api.dashboard=true # <== Enabling the dashboard to view services, middlewares, routers, etc...
        - --api.debug=true # <== Enabling additional endpoints for debugging and profiling
          ## Log Settings (options: ERROR, DEBUG, PANIC, FATAL, WARN, INFO) - https://docs.traefik.io/observability/logs/ ##
        - --log.level=ERROR # <== Setting the level of the logs from traefik
          ## Provider Settings - https://docs.traefik.io/providers/docker/#provider-configuration ##
        - --providers.docker=true # <== Enabling docker as the provider for traefik
        - --providers.docker.exposedbydefault=false # <== Don't expose every container to traefik, only expose enabled ones
        - --providers.file.directory=/etc/certs # <== Referring to a dynamic configuration file
        - --providers.docker.network=web # <== Operate on the docker network named web
          ## Entrypoints Settings - https://docs.traefik.io/routing/entrypoints/#configuration ##
        - --entrypoints.web.address=:80 # <== Defining an entrypoint for port :80 named web
        - --entrypoints.web-secured.address=:443 # <== Defining an entrypoint for https on port :443 named web-secured
        - --entrypoints.web.http.redirections.entryPoint.to=web-secured
        - --entrypoints.web.http.redirections.entryPoint.scheme=https
          ## Certificate Settings (Let's Encrypt) -  https://docs.traefik.io/https/acme/#configuration-examples ##
       # - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true # <== Enable TLS-ALPN-01 to generate and renew ACME certs
       # - --certificatesresolvers.mytlschallenge.acme.email=theafkdeveloper@gmail.com # <== Setting email for certs
       # - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json # <== Defining acme file to store cert information
    volumes:
       # - ./letsencrypt:/letsencrypt # <== Volume for certs (TLS)
        - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
        - ./dynamic/dynamic.yaml:/etc/certs/dynamic.yaml # <== Volume for dynamic conf file, **ref: line 27
        # - /etc/certs:/etc/certs
    networks:
        - web # <== Placing traefik on the network named web, to access containers on this network
    labels:
        #### Labels define the behavior and rules of the traefik proxy for this container ####
        - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
        - "traefik.http.routers.api-secured.rule=Host(`monitor.${APP_BASE_URL}`)" # <== Setting the domain for the dashboard
        - "traefik.http.routers.api-secured.tls=true"
        - "traefik.http.routers.api-secured.entrypoints=web-secured" # <== Setting the domain for the dashboard
        - "traefik.http.routers.api-secured.service=api@internal" # <== Enabling the api to be a service to access    
        - "traefik.http.routers.api-secured.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$nAvAKtX4$$ivvLR54W1xVHWsxi5EoLf0"

        - "traefik.http.routers.api.rule=Host(`monitor.${APP_BASE_URL}`)" # <== Your Domain Name for the https rule
        - "traefik.http.routers.api.entrypoints=web"
        # - "traefik.http.routers.api.service=api@internal"
        # middleware redirect
        # - "traefik.http.middlewares.api-secured.redirectscheme.scheme=https"
      # global redirect to https
        # - "traefik.http.routers.redirs.rule=hostregexp(`{${APP_BASE_URL}:.+}`)"
        # - "traefik.http.routers.redirs.entrypoints=web"
        # - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      # global http compressor
        - "traefik.http.middlewares.packet-compressor.compress=true"
        - "traefik.http.middlewares.testHeader.headers.customrequestheaders.X-Forwarded-Proto=https"

  laravel-app:
    image: buskool-app
    build:
      context: '.'
    restart: always
    container_name: bsukool-app
    environment:
        CONTAINER_ROLE: app
    volumes:
      - .:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
    networks:
    - backend
    - web

  queue:
    image: buskool-app
    container_name: laravel-queue
    restart: always
    depends_on:
      - laravel-app
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: defaultqueue
    networks:
      - backend

  queue-helper-1:
    image: buskool-app
    container_name: laravel-helper-1
    restart: always
    depends_on:
      - laravel-app
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: defaultqueue
    networks:
      - backend

  queue-helper-2:
    image: buskool-app
    container_name: laravel-helper-2
    restart: always
    depends_on:
      - laravel-app
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: smsqueue
    networks:
      - backend

  queue-helper-3:
    image: buskool-app
    container_name: laravel-helper-3
    restart: always
    depends_on:
      - laravel-app
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: smsqueue
    networks:
      - backend 
      
      
  queue-helper-4:
    image: buskool-app
    container_name: laravel-helper-4
    restart: always
    depends_on:
        - laravel-app
    volumes:
        - .:/var/www/html
    environment:
        CONTAINER_ROLE: fcmqueue
    networks:
        - backend
        
  queue-helper-5:
    image: buskool-app
    container_name: laravel-helper-5
    restart: always
    depends_on:
        - laravel-app
    volumes:
        - .:/var/www/html
    environment:
        CONTAINER_ROLE: fcmqueue
    networks:
        - backend


  queue-helper-6:
    image: buskool-app
    container_name: laravel-helper-6
    restart: always
    depends_on:
        - laravel-app
    volumes:
        - .:/var/www/html
    environment:
        CONTAINER_ROLE: mainqueue
    networks:
        - backend

    
 
networks:
  backend:
    name: backend-network
    external: false
  web:
    external: true

volumes:
    dbdata:
       driver: local
